"""
Generate agent-readable Markdown knowledge base from VASP Wiki graph data.

Uses pure [[PageName]] wikilinks — agent navigates by page name, not file paths.

Usage:
    python generate_markdown.py data/nodes.json data/edges.json --output vasp_kb/
"""

from __future__ import annotations

import json, argparse, os, re
from pathlib import Path
from collections import defaultdict

# ── Constants ─────────────────────────────────────────────────────────

SUBTYPE_LABEL = {
    "domain":        "L1 Domain",
    "tutorial":      "L2 Tutorial",
    "parameter":     "Parameter",
    "best_practice": "L3 Heuristic",
    "pitfall":       "L4 Constraint",
    "generic":       "Other",
}

SUBTYPE_ICON = {
    "domain":        " ",
    "tutorial":      "T",
    "parameter":     "P",
    "best_practice": "H",
    "pitfall":       "C",
    "generic":       "·",
}

SUBTYPE_SORT_ORDER = ["domain", "tutorial", "parameter", "best_practice", "pitfall", "generic"]

# ── Helpers ────────────────────────────────────────────────────────────


def slugify(name: str) -> str:
    """Filesystem-safe filename."""
    name = name.replace("/", "_").replace("\\", "_")
    name = name.replace(":", "_").replace("*", "_")
    name = name.replace("?", "_").replace('"', "_")
    name = name.replace("<", "_").replace(">", "_").replace("|", "_")
    if len(name) > 100:
        name = name[:100]
    return name


def first_sentence(text: str, max_len: int = 100) -> str:
    """Extract first sentence for summary."""
    if not text:
        return ""
    for sep in [". ", ".\n", ".  ", ".\r"]:
        idx = text.find(sep)
        if 10 < idx < max_len:
            return text[:idx + 1].strip()
    if len(text) > max_len:
        return text[:max_len].rsplit(" ", 1)[0] + "…"
    return text.strip()


def clean_wikilink(name: str) -> str:
    """Page name for [[wikilink]] display."""
    return name.replace("_", " ").strip()


# ── Main generator ────────────────────────────────────────────────────


def generate(nodes_path: str, edges_path: str, output_dir: str, single_file: bool = False) -> None:
    """Generate agent-friendly markdown knowledge base."""

    with open(nodes_path, "r", encoding="utf-8") as f:
        nodes_list = json.load(f)
    with open(edges_path, "r", encoding="utf-8") as f:
        edges_list = json.load(f)

    # ── Load link contexts (generated by enrich_nodes.py) ──
    link_contexts_path = nodes_path.replace(".json", "_link_contexts.json")
    link_contexts: dict[str, str] = {}
    if os.path.exists(link_contexts_path):
        with open(link_contexts_path, "r", encoding="utf-8") as f:
            link_contexts = json.load(f)

    # ── Lookup structures ──
    nodes: dict[str, dict] = {}
    for n in nodes_list:
        nodes[n["id"]] = n

    # Outgoing: page_id → [(target_id, relation)]
    outgoing: dict[str, list[tuple[str, str]]] = defaultdict(list)
    # Incoming: page_id → [(source_id, relation)]
    incoming: dict[str, list[tuple[str, str]]] = defaultdict(list)

    for e in edges_list:
        src, tgt, rel = e["source"], e["target"], e["relation"]
        if src in nodes and tgt in nodes:
            outgoing[src].append((tgt, rel))
            incoming[tgt].append((src, rel))

    # Group by subtype
    by_subtype: dict[str, list[dict]] = defaultdict(list)
    for n in nodes.values():
        by_subtype[n.get("subtype", "generic")].append(n)

    # Group by category
    by_category: dict[str, list[dict]] = defaultdict(list)
    for n in nodes.values():
        cat = n.get("category", "") or "Uncategorized"
        by_category[cat].append(n)

    os.makedirs(output_dir, exist_ok=True)

    # ══════════════════════════════════════════════════════════════════
    # 1. Generate individual page files
    # ══════════════════════════════════════════════════════════════════

    generated = 0
    for n in nodes.values():
        nid = n["id"]
        subtype = n.get("subtype", "generic")

        # Build outgoing links section (with context from link_contexts)
        out_links = _build_link_sections(nid, outgoing, nodes, link_contexts)
        # Build incoming refs (top 10 most relevant)
        in_refs = _build_incoming_refs(nid, incoming, nodes, link_contexts, limit=10)

        md = _render_page(n, out_links, in_refs)

        filename = slugify(nid) + ".md"
        filepath = os.path.join(output_dir, filename)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(md)
        generated += 1

    print(f"  Generated {generated} page files")

    # ══════════════════════════════════════════════════════════════════
    # 2. Generate index.md
    # ══════════════════════════════════════════════════════════════════

    index_md = _render_index(by_subtype, nodes)
    with open(os.path.join(output_dir, "index.md"), "w", encoding="utf-8") as f:
        f.write(index_md)
    print(f"  Generated index.md")

    # ══════════════════════════════════════════════════════════════════
    # 3. Generate category indexes
    # ══════════════════════════════════════════════════════════════════

    cat_dir = os.path.join(output_dir, "categories")
    os.makedirs(cat_dir, exist_ok=True)
    for cat, members in sorted(by_category.items()):
        cat_md = _render_category_index(cat, members)
        cat_slug = slugify(cat) if cat else "Uncategorized"
        with open(os.path.join(cat_dir, f"{cat_slug}.md"), "w", encoding="utf-8") as f:
            f.write(cat_md)
    print(f"  Generated {len(by_category)} category indexes")

    # ── Stats ──
    total_edges = len(edges_list)
    # ══════════════════════════════════════════════════════════════════
    # 4. Generate graph_index.md (relation-based global index)
    # ══════════════════════════════════════════════════════════════════

    graph_idx = _render_graph_index(nodes, outgoing, incoming, edges_list, link_contexts, by_subtype)
    with open(os.path.join(output_dir, "graph_index.md"), "w", encoding="utf-8") as f:
        f.write(graph_idx)
    print(f"  Generated graph_index.md")

    # ══════════════════════════════════════════════════════════════════
    # 5. Generate single-file kb.md (optional, agent-friendly)
    # ══════════════════════════════════════════════════════════════════

    if single_file:
        kb_md = _render_single_file(nodes, outgoing, incoming, by_subtype, link_contexts)
        sf_path = os.path.join(output_dir, "kb.md")
        with open(sf_path, "w", encoding="utf-8") as f:
            f.write(kb_md)
        size_kb = os.path.getsize(sf_path) / 1024
        print(f"  Generated kb.md ({size_kb:.0f} KB)")

    print(f"\n=== Knowledge base generated ===")
    print(f"  Output: {os.path.abspath(output_dir)}")
    print(f"  Nodes:  {len(nodes)} | Edges: {total_edges}")
    for st in SUBTYPE_SORT_ORDER:
        cnt = len(by_subtype.get(st, []))
        if cnt:
            print(f"    {SUBTYPE_LABEL.get(st, st)}: {cnt}")


# ── Link builders ──────────────────────────────────────────────────────


def _build_link_sections(
    nid: str,
    outgoing: dict[str, list[tuple[str, str]]],
    nodes: dict[str, dict],
    contexts: dict[str, str],
) -> str:
    """Build 'See Also' and 'Belongs To' sections with context descriptions."""

    links = outgoing.get(nid, [])
    if not links:
        return ""

    wikilinks: list[str] = []
    belongs_to: list[str] = []
    subcats: list[str] = []
    contains: list[str] = []

    seen = set()
    for tgt, rel in links:
        if tgt in seen:
            continue
        tgt_title = nodes.get(tgt, {}).get("title", clean_wikilink(tgt))
        icon = SUBTYPE_ICON.get(nodes.get(tgt, {}).get("subtype", "generic"), "")
        line = f"- `{icon}` [[{clean_wikilink(tgt)}|{tgt_title}]]"

        # Add context description
        ctx = contexts.get(tgt, "")
        if ctx and len(ctx) > 10:
            short_ctx = ctx[:100]
            if len(ctx) > 100:
                short_ctx = short_ctx.rsplit(" ", 1)[0] + "…"
            line += f" — *{short_ctx}*"

        if rel == "belongs_to":
            belongs_to.append(line)
        elif rel == "has_subcategory":
            subcats.append(line)
        elif rel == "contains":
            contains.append(line)
        else:
            wikilinks.append(line)
        seen.add(tgt)

    lines = []
    if belongs_to:
        lines.append("## Belongs To\n")
        lines.extend(belongs_to)
        lines.append("")
    if wikilinks:
        lines.append("## See Also\n")
        lines.extend(wikilinks)
        lines.append("")
    if subcats:
        lines.append("## Subcategories\n")
        lines.extend(subcats)
        lines.append("")
    if contains:
        lines.append("## Contains\n")
        lines.extend(contains)
        lines.append("")

    return "\n".join(lines)


def _build_incoming_refs(
    nid: str,
    incoming: dict[str, list[tuple[str, str]]],
    nodes: dict[str, dict],
    contexts: dict[str, str],
    limit: int = 10,
) -> str:
    """Build 'Referenced By' section — top N by link count, with context."""
    in_links = incoming.get(nid, [])
    if not in_links:
        return ""

    counts: dict[str, int] = defaultdict(int)
    for src, rel in in_links:
        counts[src] += 1

    sorted_refs = sorted(counts.items(), key=lambda x: (-x[1], x[0]))[:limit]

    lines = ["## Referenced By\n"]
    for src, cnt in sorted_refs:
        src_title = nodes.get(src, {}).get("title", clean_wikilink(src))
        icon = SUBTYPE_ICON.get(nodes.get(src, {}).get("subtype", "generic"), "")
        line = f"- `{icon}` [[{clean_wikilink(src)}|{src_title}]]"
        ctx = contexts.get(src, "")
        if ctx and len(ctx) > 10:
            short_ctx = ctx[:100]
            if len(ctx) > 100:
                short_ctx = short_ctx.rsplit(" ", 1)[0] + "…"
            line += f" — *{short_ctx}*"
        lines.append(line)

    if len(counts) > limit:
        lines.append(f"\n_... and {len(counts) - limit} more pages_")

    return "\n".join(lines) + "\n"


# ── Page renderer ─────────────────────────────────────────────────────


def _render_page(
    node: dict,
    out_links: str,
    in_refs: str,
) -> str:
    """Render a single markdown page."""

    nid = node["id"]
    title = node.get("title", nid.replace("_", " "))
    subtype = node.get("subtype", "generic")
    category = node.get("category", "")
    tags = node.get("tags", [])
    aliases = node.get("aliases", [])
    content = node.get("content", "")

    label = SUBTYPE_LABEL.get(subtype, subtype)
    icon = SUBTYPE_ICON.get(subtype, "")

    lines = []
    # ── Frontmatter ──
    lines.append("---")
    lines.append(f"id: {nid}")
    lines.append(f"title: \"{title}\"")
    lines.append(f"type: {node.get('entry_type', 'unknown')}")
    lines.append(f"subtype: {subtype}")
    if category:
        lines.append(f"category: \"{category}\"")
    if tags:
        lines.append(f"tags: [{', '.join(tags)}]")
    if aliases:
        lines.append(f"aliases: [{', '.join(aliases)}]")
    lines.append("---")
    lines.append("")

    # ── Title + metadata badge ──
    lines.append(f"# `{icon}` {title}")
    lines.append("")
    lines.append(f"> **{label}**")
    if category:
        lines.append(f"> Category: [[{clean_wikilink(category)}]]")
    if tags:
        lines.append(f"> Tags: " + " · ".join(f"`{t}`" for t in tags[:8]))
    if aliases:
        lines.append(f"> Aliases: " + " · ".join(aliases[:5]))
    lines.append("")
    lines.append("---")
    lines.append("")

    # ── Structured data ──
    structured = node.get("structured", {})

    # Quick Facts table for parameters
    qf = structured.get("quick_facts")
    if qf:
        lines.append("## Quick Facts\n")
        lines.append(f"| | |")
        lines.append(f"|---|---|")
        lines.append(f"| **Type** | `{qf.get('type', '?')}` |")
        lines.append(f"| **Default** | `{qf.get('default', '?')}` |")
        lines.append("")
        if qf.get("raw_description"):
            lines.append(qf["raw_description"])
            lines.append("")
        lines.append("---")
        lines.append("")

    if structured.get("definition"):
        lines.append(f"**Definition:** {structured['definition']}")
        lines.append("")

    options = structured.get("options")
    if options:
        lines.append("## Options\n")
        for o in options:
            desc = f" — {o['description']}" if o.get("description") else ""
            lines.append(f"- `{o['value']}`{desc}")
        lines.append("")

    warnings = structured.get("warnings")
    if warnings:
        lines.append("## Warnings\n")
        for w in warnings:
            lines.append(f"> {w}")
        lines.append("")

    # Tutorial summary
    ts = structured.get("tutorial_summary")
    if ts:
        lines.append("## Structured Summary\n")
        lines.append(ts)
        lines.append("")
        lines.append("---")
        lines.append("")

    # ── Raw Content (for fallback / more detail) ──
    # For parameters with quick facts, skip raw content to save context
    if not qf:
        lines.append("## Content\n")
        if content:
            lines.append(content)
        else:
            lines.append("_No content extracted._")
        lines.append("")

    # ── Links ──
    if out_links:
        lines.append("---")
        lines.append("")
        lines.append(out_links)

    if in_refs:
        lines.append("---")
        lines.append("")
        lines.append(in_refs)

    return "\n".join(lines)


# ── Index renderer ────────────────────────────────────────────────────


def _render_index(
    by_subtype: dict[str, list[dict]],
    nodes: dict[str, dict],
) -> str:
    """Render the master index."""

    total = len(nodes)
    lines = []
    lines.append("# VASP Knowledge Graph")
    lines.append("")
    lines.append(f"> **{total} nodes** — agent-readable knowledge base")
    lines.append("")
    lines.append("Navigate via `[[wikilink]]` syntax. Start from a Domain or search for a Parameter.")
    lines.append("")
    lines.append("---")
    lines.append("")

    # ── Quick TOC ──
    lines.append("## Contents\n")
    for st in SUBTYPE_SORT_ORDER:
        items = by_subtype.get(st, [])
        if not items:
            continue
        label = SUBTYPE_LABEL.get(st, st)
        anchor = label.lower().replace(" ", "-")
        lines.append(f"- [{label}](#{anchor}) — {len(items)} pages")
    lines.append("")

    # ── Each subtype section ──
    for st in SUBTYPE_SORT_ORDER:
        items = by_subtype.get(st, [])
        if not items:
            continue
        label = SUBTYPE_LABEL.get(st, st)
        icon = SUBTYPE_ICON.get(st, "")

        lines.append("---")
        lines.append("")
        lines.append(f"## `{icon}` {label}\n")

        # Group by category
        by_cat: dict[str, list[dict]] = defaultdict(list)
        for n in items:
            cat = n.get("category", "Uncategorized")
            by_cat[cat].append(n)

        for cat in sorted(by_cat.keys()):
            members = by_cat[cat]
            if len(by_cat) > 1:
                lines.append(f"### {cat}\n")
            for n in sorted(members, key=lambda x: x.get("title", x["id"]).lower()):
                title = n.get("title", n["id"].replace("_", " "))
                defn = (n.get("structured", {}) or {}).get("definition", "")
                line = f"- [[{clean_wikilink(n['id'])}|{title}]]"
                if defn:
                    line += f" — {defn[:100]}"
                lines.append(line)
            lines.append("")

    return "\n".join(lines)


# ── Category index renderer ───────────────────────────────────────────


def _render_category_index(cat: str, members: list[dict]) -> str:
    """Render a category-level index page."""
    lines = [f"# Category: {cat}\n"]

    by_st: dict[str, list[dict]] = defaultdict(list)
    for n in members:
        by_st[n.get("subtype", "generic")].append(n)

    for st in SUBTYPE_SORT_ORDER:
        items = by_st.get(st, [])
        if not items:
            continue
        lines.append(f"## {SUBTYPE_LABEL.get(st, st)}\n")
        for n in sorted(items, key=lambda x: x.get("title", x["id"])):
            title = n.get("title", n["id"].replace("_", " "))
            summary = first_sentence(n.get("content", ""), 80)
            line = f"- [[{clean_wikilink(n['id'])}|{title}]]"
            if summary:
                line += f" — {summary}"
            lines.append(line)
        lines.append("")

    return "\n".join(lines)


# ── Graph index renderer ───────────────────────────────────────────────


def _render_graph_index(
    nodes: dict[str, dict],
    outgoing: dict[str, list[tuple[str, str]]],
    incoming: dict[str, list[tuple[str, str]]],
    edges_list: list[dict],
    contexts: dict[str, str],
    by_subtype: dict[str, list[dict]],
) -> str:
    """Render a global index based on graph relationships."""

    lines = []
    lines.append("# Graph Index")
    lines.append("")
    lines.append("Global relationship index. Use this to discover pages by how they connect to each other.")
    lines.append("")

    subtype_order = ["domain", "tutorial", "parameter", "best_practice", "pitfall", "generic"]

    # ── 1. Hub pages (highest degree) ──
    degree: dict[str, int] = {}
    for nid in nodes:
        degree[nid] = len(outgoing.get(nid, [])) + len(incoming.get(nid, []))
    hubs = sorted(degree.items(), key=lambda x: -x[1])[:30]

    lines.append("---")
    lines.append("")
    lines.append("## Hub Pages")
    lines.append("")
    lines.append("Top 30 pages by total connections:")
    lines.append("")
    lines.append("| # | Page | Out | In | Total | Type |")
    lines.append("|---|------|-----|-----|-------|------|")
    for i, (nid, deg) in enumerate(hubs, 1):
        n = nodes.get(nid, {})
        out_n = len(outgoing.get(nid, []))
        in_n = len(incoming.get(nid, []))
        subtype = n.get("subtype", "generic")
        title = n.get("title", nid.replace("_", " "))
        ctx = contexts.get(nid, "")
        if ctx and len(ctx) > 60:
            ctx = ctx[:60].rsplit(" ", 1)[0] + "..."
        lines.append(f"| {i} | [[{clean_wikilink(nid)}\\|{title}]] | {out_n} | {in_n} | {deg} | {subtype} |")
    lines.append("")

    # ── 2. By relation type ──
    lines.append("---")
    lines.append("")
    lines.append("## By Relation Type")
    lines.append("")

    rel_labels = {
        "contains": "Contains (category members)",
        "has_subcategory": "Has Subcategory",
        "belongs_to": "Belongs To",
        "wikilink": "Wikilinks (cross-references)",
    }

    for rel, label in rel_labels.items():
        rel_edges = [e for e in edges_list if e["relation"] == rel
                     and e["source"] in nodes and e["target"] in nodes]
        if not rel_edges:
            continue

        # Top sources for this relation
        src_counts: dict[str, int] = defaultdict(int)
        tgt_counts: dict[str, int] = defaultdict(int)
        for e in rel_edges:
            src_counts[e["source"]] += 1
            tgt_counts[e["target"]] += 1

        lines.append(f"### {label}")
        lines.append("")
        lines.append(f"{len(rel_edges)} edges, {len(src_counts)} sources, {len(tgt_counts)} targets")
        lines.append("")

        top_src = sorted(src_counts.items(), key=lambda x: -x[1])[:10]
        top_tgt = sorted(tgt_counts.items(), key=lambda x: -x[1])[:10]

        lines.append("Top sources:")
        lines.append("")
        for nid, cnt in top_src:
            n = nodes.get(nid, {})
            title = n.get("title", nid.replace("_", " "))
            lines.append(f"- [[{clean_wikilink(nid)}|{title}]] ({cnt})")
        lines.append("")

        lines.append("Top targets:")
        lines.append("")
        for nid, cnt in top_tgt:
            n = nodes.get(nid, {})
            title = n.get("title", nid.replace("_", " "))
            lines.append(f"- [[{clean_wikilink(nid)}|{title}]] ({cnt})")
        lines.append("")

    # ── 3. Subtype cross-reference matrix ──
    lines.append("---")
    lines.append("")
    lines.append("## Subtype Cross-Reference")
    lines.append("")
    lines.append("Edge counts between node types (source row -> target column):")
    lines.append("")
    lines.append("| Source \\ Target | " + " | ".join(subtype_order) + " |")
    lines.append("|" + "---|" * (len(subtype_order) + 1))

    for src_st in subtype_order:
        row = [src_st]
        for tgt_st in subtype_order:
            cnt = 0
            for e in edges_list:
                src = nodes.get(e["source"])
                tgt = nodes.get(e["target"])
                if src and tgt and src.get("subtype") == src_st and tgt.get("subtype") == tgt_st:
                    cnt += 1
            row.append(str(cnt))
        lines.append("| " + " | ".join(row) + " |")
    lines.append("")

    # ── 4. Orphan pages (no incoming links) ──
    lines.append("---")
    lines.append("")
    lines.append("## Orphan Pages")
    lines.append("")
    orphans = [nid for nid in nodes if not incoming.get(nid)]
    lines.append(f"{len(orphans)} pages with no incoming links (not referenced by any other page):")
    lines.append("")
    for nid in sorted(orphans)[:50]:
        n = nodes.get(nid, {})
        title = n.get("title", nid.replace("_", " "))
        lines.append(f"- [[{clean_wikilink(nid)}|{title}]]")
    if len(orphans) > 50:
        lines.append(f"- ... and {len(orphans) - 50} more")
    lines.append("")

    return "\n".join(lines)


# ── Single-file renderer ────────────────────────────────────────────────


def _render_single_file(
    nodes: dict[str, dict],
    outgoing: dict[str, list[tuple[str, str]]],
    incoming: dict[str, list[tuple[str, str]]],
    by_subtype: dict[str, list[dict]],
    contexts: dict[str, str],
) -> str:
    """Render all pages into a single kb.md file."""

    subtype_order = ["domain", "tutorial", "parameter", "best_practice", "pitfall", "generic"]

    # ── Index ──
    lines = []
    lines.append("# VASP Knowledge Base")
    lines.append("")
    lines.append(f"{len(nodes)} pages. Use [[wikilink]] to navigate, YAML frontmatter to filter.")
    lines.append("")
    lines.append("## Index")
    lines.append("")

    for st in subtype_order:
        items = by_subtype.get(st, [])
        if not items:
            continue
        lines.append(f"### {SUBTYPE_LABEL.get(st, st)}")
        lines.append("")
        for n in sorted(items, key=lambda x: (x.get("title", x["id"]) or "").lower()):
            nid = n["id"]
            title = n.get("title", nid.replace("_", " "))
            defn = (n.get("structured", {}) or {}).get("definition", "")
            tags_str = ""
            tags = n.get("tags", [])
            if tags:
                tags_str = " `" + "` `".join(tags[:3]) + "`"
            line = f"- [[{clean_wikilink(nid)}|{title}]]"
            if defn:
                line += f" — {defn[:100]}"
            if tags_str:
                line += f" {tags_str}"
            lines.append(line)
        lines.append("")

    # ── Pages ──
    for st in subtype_order:
        items = sorted(by_subtype.get(st, []), key=lambda x: (x.get("title", x["id"]) or "").lower())
        for n in items:
            nid = n["id"]
            lines.append("---")
            lines.append("")
            lines.extend(_render_page_frontmatter(n))
            lines.append("")
            lines.append(f"# {n.get('title', nid.replace('_', ' '))}")
            lines.append("")

            subtype = n.get("subtype", "generic")
            label = SUBTYPE_LABEL.get(subtype, subtype)

            qf = n.get("structured", {}).get("quick_facts")
            if qf:
                lines.append(f"> {label}")
                lines.append("")
                lines.append("## Quick Facts")
                lines.append("")
                lines.append(f"- Type: {qf.get('type', '?')}")
                lines.append(f"- Default: {qf.get('default', '?')}")
                if qf.get("raw_description"):
                    lines.append("")
                    lines.append(qf["raw_description"])

            s = n.get("structured", {})
            if s.get("definition"):
                lines.append("")
                lines.append(f"**Definition:** {s['definition']}")

            options = s.get("options")
            if options:
                lines.append("")
                lines.append("## Options")
                lines.append("")
                for o in options:
                    desc = f" — {o['description']}" if o.get("description") else ""
                    lines.append(f"- `{o['value']}`{desc}")

            warnings = s.get("warnings")
            if warnings:
                lines.append("")
                lines.append("## Warnings")
                lines.append("")
                for w in warnings:
                    lines.append(f"> {w}")

            ts = n.get("structured", {}).get("tutorial_summary")
            if ts:
                lines.append(f"> {label}")
                lines.append("")
                lines.append("## Summary")
                lines.append("")
                lines.append(ts)

            content = n.get("content", "")
            if content and not qf:
                lines.append("")
                lines.append(content)

            # Links
            out_links = outgoing.get(nid, [])
            if out_links:
                lines.append("")
                lines.append("## See Also")
                lines.append("")
                seen = set()
                for tgt, rel in out_links:
                    if tgt in seen:
                        continue
                    seen.add(tgt)
                    tgt_node = nodes.get(tgt, {})
                    tgt_title = tgt_node.get("title", clean_wikilink(tgt))
                    ctx = contexts.get(tgt, "")
                    if ctx and len(ctx) > 100:
                        ctx = ctx[:100].rsplit(" ", 1)[0]
                    line = f"- [[{clean_wikilink(tgt)}|{tgt_title}]]"
                    if ctx:
                        line += f" — {ctx}"
                    lines.append(line)

            # Referenced by
            in_refs = incoming.get(nid, [])
            if in_refs:
                counts: dict[str, int] = defaultdict(int)
                for src, _ in in_refs:
                    counts[src] += 1
                top_refs = sorted(counts.items(), key=lambda x: -x[1])[:10]
                lines.append("")
                lines.append("## Referenced By")
                lines.append("")
                for src, cnt in top_refs:
                    src_node = nodes.get(src, {})
                    src_title = src_node.get("title", clean_wikilink(src))
                    lines.append(f"- [[{clean_wikilink(src)}|{src_title}]]")

            lines.append("")

    return "\n".join(lines)


def _render_page_frontmatter(n: dict) -> list[str]:
    """Return YAML frontmatter lines for a node."""
    fm = []
    fm.append("---")
    fm.append(f"id: {n['id']}")
    fm.append(f"title: \"{n.get('title', n['id'])}\"")
    fm.append(f"type: {n.get('entry_type', 'unknown')}")
    fm.append(f"subtype: {n.get('subtype', 'generic')}")
    cat = n.get("category", "")
    if cat:
        fm.append(f"category: \"{cat}\"")
    tags = n.get("tags", [])
    if tags:
        fm.append(f"tags: [{', '.join(tags)}]")
    fm.append("---")
    return fm


# ── CLI ────────────────────────────────────────────────────────────────


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate agent-readable Markdown")
    parser.add_argument("nodes", help="Path to nodes.json")
    parser.add_argument("edges", help="Path to edges.json")
    parser.add_argument("--output", "-o", default="vasp_kb", help="Output directory")
    parser.add_argument("--single-file", action="store_true", help="Also generate a single kb.md")
    args = parser.parse_args()

    generate(args.nodes, args.edges, args.output, single_file=args.single_file)
